### ISSUE TITLE
Комментарии в коде JS

### ISSUE THREAD

**Issue by rame0** [rees46/rees46_magento#1]
Измените способ комментирования в коде JS модуля с // на /**/, иначе, при "минификации" строка комментария объединяется со строкой кода js и получается, что часть кода закомментирована. Как результат, модуль не работает

**Comment by noff** [comment]
Странная минификация, которая не удаляет комментарии перед началом сжатия кода. Это какой минификатор?

**Comment by rame0** [comment]
Согласен, странная.
На самом деле, я отключил плагин, который сокращал код, сбросил кэши и все остальное. Плагин отключился, но код JS все равно объединяется с коментарием. Не могу сказать, кто это делает, сама админка или какой то еще плагин.

**Comment by noff** [comment]
Выложено в 3.3.4
